"""initial tables

Revision ID: 573da4fb16f8
Revises:
Create Date: 2026-03-20 23:24:08.404485

"""

from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa

import pgvector


# revision identifiers, used by Alembic.
revision: str = "573da4fb16f8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=127), nullable=False),
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index("index_categories_name", "categories", ["name"], unique=False)
    op.create_index("index_categories_slug", "categories", ["slug"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=511), nullable=False),
        sa.Column(
            "type",
            sa.Enum("TELEGRAM", "WEB", "API", "MANUAL", name="sourcetype"),
            nullable=False,
        ),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("last_scraped_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index("index_sources_type", "sources", ["type"], unique=False)
    op.create_index("index_sources_url", "sources", ["url"], unique=False)
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("text_hash"),
    )
    op.create_index(
        "index_questions_category", "questions", ["category_id"], unique=False
    )
    op.create_index(
        "index_questions_created", "questions", ["created_at"], unique=False
    )
    op.create_index("index_questions_source", "questions", ["source_id"], unique=False)
    op.create_index(
        "index_questions_text_hash", "questions", ["text_hash"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("index_questions_text_hash", table_name="questions")
    op.drop_index("index_questions_source", table_name="questions")
    op.drop_index("index_questions_created", table_name="questions")
    op.drop_index("index_questions_category", table_name="questions")
    op.drop_table("questions")
    op.drop_index("index_sources_url", table_name="sources")
    op.drop_index("index_sources_type", table_name="sources")
    op.drop_table("sources")
    op.drop_index("index_categories_slug", table_name="categories")
    op.drop_index("index_categories_name", table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
